

export const metadata = {
  title: "Contact",
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>Contact page aapka tahe dil se swagat krta hai!!!{children}</body>
    </html>
  )
}
